//  Label StoreMAX
//
//  Created by Anthony Gordon.
//  Copyright © 2019 WooSignal. All rights reserved.
//

//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

var appCountryOptions = [
  {"code": "*", "title": "Match all states"},
  {"code": "AL", "title": "Alabama"},
  {"code": "AK", "title": "Alaska"},
  {"code": "AS", "title": "American Samoa"},
  {"code": "AZ", "title": "Arizona"},
  {"code": "AR", "title": "Arkansas"},
  {"code": "CA", "title": "California"},
  {"code": "CO", "title": "Colorado"},
  {"code": "CT", "title": "Connecticut"},
  {"code": "DE", "title": "Delaware"},
  {"code": "DC", "title": "District Of Columbia"},
  {"code": "FM", "title": "Federated States Of Micronesia"},
  {"code": "FL", "title": "Florida"},
  {"code": "GA", "title": "Georgia"},
  {"code": "GU", "title": "Guam"},
  {"code": "HI", "title": "Hawaii"},
  {"code": "ID", "title": "Idaho"},
  {"code": "IL", "title": "Illinois"},
  {"code": "IN", "title": "Indiana"},
  {"code": "IA", "title": "Iowa"},
  {"code": "KS", "title": "Kansas"},
  {"code": "KY", "title": "Kentucky"},
  {"code": "LA", "title": "Louisiana"},
  {"code": "ME", "title": "Maine"},
  {"code": "MH", "title": "Marshall Islands"},
  {"code": "MD", "title": "Maryland"},
  {"code": "MA", "title": "Massachusetts"},
  {"code": "MI", "title": "Michigan"},
  {"code": "MN", "title": "Minnesota"},
  {"code": "MS", "title": "Mississippi"},
  {"code": "MO", "title": "Missouri"},
  {"code": "MT", "title": "Montana"},
  {"code": "NE", "title": "Nebraska"},
  {"code": "NV", "title": "Nevada"},
  {"code": "NH", "title": "New Hampshire"},
  {"code": "NJ", "title": "New Jersey"},
  {"code": "NM", "title": "New Mexico"},
  {"code": "NY", "title": "New York"},
  {"code": "NC", "title": "North Carolina"},
  {"code": "ND", "title": "North Dakota"},
  {"code": "MP", "title": "Northern Mariana Islands"},
  {"code": "OH", "title": "Ohio"},
  {"code": "OK", "title": "Oklahoma"},
  {"code": "OR", "title": "Oregon"},
  {"code": "PW", "title": "Palau"},
  {"code": "PA", "title": "Pennsylvania"},
  {"code": "PR", "title": "Puerto Rico"},
  {"code": "RI", "title": "Rhode Island"},
  {"code": "SC", "title": "South Carolina"},
  {"code": "SD", "title": "South Dakota"},
  {"code": "TN", "title": "Tennessee"},
  {"code": "TX", "title": "Texas"},
  {"code": "UT", "title": "Utah"},
  {"code": "VT", "title": "Vermont"},
  {"code": "VI", "title": "Virgin Islands"},
  {"code": "VA", "title": "Virginia"},
  {"code": "WA", "title": "Washington"},
  {"code": "WV", "title": "West Virginia"},
  {"code": "WI", "title": "Wisconsin"},
  {"code": "WY", "title": "Wyoming"}
];
